# config file for varicity
# you may alter this file before running the program
# pick your color at https://htmlcolorcodes.com/

building:
  padding: 0.2
  colors:
    # outline: "#145a32" # dark green
    # edges: "#a569bd" # light purple
    faces: # ordered by importance, descending : in case of conflict, the first color to match will be displayed
      - name: "!HOTSPOT"
        color: "#555555"
      - name: "VP"
        color: "#FF6F33"
      - name: "STRATEGY"
        color: "#17202a" # black
      - name: "FACTORY"
        color: "#7d3c98" # purple
      - name: "INTERFACE"
        color: "#e67e22" # orange
      - name: "ABSTRACT"
        color: "#2c3e50" # dark blue
      - name: "CLASS"
        color: "#335DFF"

    edges:
      - name: "API"
        color: "#000000"

    outlines:
#      - name: "API"
#        color: "#FF0000"
# - name: "CLASS"
# color: "#000000"

district:
  padding: 0
  colors:
    faces:
      - name: "PACKAGE"
        color: "#801A2E"
      - name: "VP"
        color: "#1A8039"

link:
  colors:
    - name: "IMPLEMENTS"
      color: "#ef2222"
    - name: "EXTENDS"
      color: "#3f97ff"
    - name: "DUPLICATES"
      color: "#2B914A"
    - name: "INSTANTIATE"
      color: "#1A8039"
  display:
    air_traffic:
      - "IMPLEMENTS"
      - "EXTENDS"
    underground_road:
      - "INSTANTIATE"

hierarchy_links:
  - "INSTANTIATE"
  - "IMPLEMENTS"
  - "EXTENDS"

blacklist: #all classes that must not appear
  - "org.jfree.chart.util.PublicCloneable"
  - "org.jfree.chart.event"
  - "org.jfree.data.general"

api_classes: # configuration given in the paper
  argoUML-bcae373: # 2, IN/OUT
    - "org.argouml.cognitive.Designer"
    - "org.argouml.uml.ui.UMLModelElementListModel2"
    - "org.argouml.uml.diagram.ui.FigNodeModelElement"
  awt-jb8u202-b1532: #3, IN/OUT
    - "java.awt.Shape"
  cucumber-v6.8.0: # 11, IN/OUT
    - "io.cucumber.plugin.event.Event"
    - "io.cucumber.java.StepDefinitionAnnotation"
  cxf-cxf-3.2.7: # 6, OUT
    - "org.apache.cxf.endpoint.Endpoint"
  jfreechart-v1.5.0: # 2, OUT
    - "org.jfree.chart.JFreeChart"
    - "org.jfree.chart.plot.Plot"
  junit-r4.12: # 3 IN/OUT
    - "org.junit.Assert"
    - "org.junit.rules.TestRule"
  logbook-2.2.1: # 4, OUT
    - "org.zalando.logbook.Logbook"
    - "org.zalando.logbook.Sink"
  maven-maven-3.6.0: # 7, OUT
    - "org.apache.maven.Maven"
    - "org.apache.maven.execution.MavenSession"
  netbeans-12.2: # 5, IN/OUT
    - "org.netbeans.api.java.platform.JavaPlatform"
  riptide-2.11.0: # 6, IN/OUT
    - "org.zalando.riptide.Http"

variables: #variables to be used for width and height of a building
  width: "nbConstructorVariants"
  height: "nbMethodVariants"

orientation: "OUT"

default_level: 4